version: "3.7"

services:
  rtsp:
    build: rtsp
    restart: unless-stopped
    network_mode: host
    ports:
      - 8554:8554
      - 8888:8888
      - 8889:8889
    volumes:
      - ./rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./rtsp/scripts:/scripts
      - ${LIGHT_STORES_DIR}/kv:/config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  pygateway:
    build: pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    restart: unless-stopped
    network_mode: host
    environment:
      BROKER_HOST: ${BROKER_HOST:-localhost}
      DEBUG_PYGATEWAY: ${DEBUG_PYGATEWAY:-false}
  goo:
    build:
      context: .
      dockerfile: goo/Dockerfile
    command: -basePath ${LIGHT_STORES_DIR}
    restart: unless-stopped
    network_mode: host
    environment:
      OBS_LANDSCAPE_URL: ${OBS_LANDSCAPE_URL}
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      ENABLE_SCHEDULER: ${ENABLE_SCHEDULER}
    volumes:
      - ${LIGHT_STORES_DIR}:${LIGHT_STORES_DIR}
      - /dev:/dev
    user: "1000:1000"
  dslrcapture:
    build:
      context: .
      dockerfile: dslrcapture/Dockerfile
    command: -basePath ${LIGHT_STORES_DIR}
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MOCK_DSLR: ${MOCK_DSLR:-false}
      OBS_LANDSCAPE_URL: ${OBS_LANDSCAPE_URL}
    volumes:
      - ${LIGHT_STORES_DIR}:${LIGHT_STORES_DIR}
      - /dev:/dev
      - ./tools:/tools
      - ./resources:/resources
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:80"
