version: "3.7"


services:
  rtsp:
    build: services/rtsp
    restart: unless-stopped
    network_mode: host
    ports:
      - 8554:8554
    volumes:
      - ./services/rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./services/rtsp/scripts:/scripts
      - ./config:/config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  pygateway:
    build: services/pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    restart: unless-stopped
    network_mode: host
    environment:
      BROKER_HOST: ${BROKER_HOST:-localhost}
      DEBUG_PYGATEWAY: ${DEBUG_PYGATEWAY:-false}
  goo:
    build: services/goo
    command: -basePath ${LIGHT_STORES_DIR}
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      MOCK_DSLR: ${MOCK_DSLR:-false}
    volumes:
      - ${LIGHT_STORES_DIR}:${LIGHT_STORES_DIR}
      - /dev:/dev
      - ./user-tools:/src/user-tools
      - ./resources:/src/resources